### ISSUE TITLE
ts-node 6 breaks compilation

### ISSUE THREAD

**Issue by Nosfistis** [mean-expert-official/fireloop.io#144]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

After generating a new project (or updating an old one's ts-node version to 6+), using [pm2](http://pm2.keymetrics.io/) to start `server.js`. The error message shows ts-node complaining about experimental decorators in Typescript, although they are declared in tsconfig.

The issue occurs on a specific file (although it probably is just the first file to be required), which works fine with ts-node 5.0.1.

Since the only change in [ts-node 6](https://github.com/TypeStrong/ts-node/releases/tag/v6.0.0) is reverting to type-check by default, perhaps the new flag `-T` should be used to avoid it.

Error log:
Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (1219)
    at getOutput (.\api\node_modules\ts-node\src\index.ts:329:15)
    at Object.compile (.\api\node_modules\ts-node\src\index.ts:515:11)
    at Module.m._compile (.\api\node_modules\ts-node\src\index.ts:402:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.require.extensions.(anonymous function) [as .ts] (.\api\node_modules\ts-node\src\index.ts:405:12)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireNodeOrEsModule (.\api\node_modules\loopback-boot\lib\require.js:7:17)
    at .\api\node_modules\loopback-boot\lib\executor.js:248:20
    at Array.forEach (<anonymous>)
    at defineModels (.\api\node_modules\loopback-boot\lib\executor.js:229:23)
    at setupModels (.\api\node_modules\loopback-boot\lib\executor.js:197:3)
    at execute (.\api\node_modules\loopback-boot\lib\executor.js:40:3)

**Comment by imvasen** [comment]
Did you solved it? Or did you go back with v5.x.x? I'm having the same problems.

**Comment by Nosfistis** [comment]
Ts-node v7 works fine. No problem there.
