### ISSUE TITLE
server app is Crashing 

### ISSUE THREAD

**Issue by ittechsathish** [mean-expert-official/fireloop.io#88]
#### What type of issue are you creating?
- [*] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Today i installed fireloop in my local using CLI.

when i am starting the server, the app is crashing with below message.

--------------------------------------------
 if (!options.driver.options) {
                                   ^
TypeError: Cannot read property 'options' of undefined
    at EventEmitter.<anonymous> (D:\project\source\fireloop\node_modules\@mean-expert\loopback-component-realtime\dist\index.js:24:36)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Server.<anonymous> (D:\project\source\fireloop\server\server.js:14:9)
    at Server.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1288:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

----------------------------------------------------------------------------

**Comment by hellraiserii** [comment]
It happened to me yesterday when I npm-installed packages in my project. You probably caught "@mean-expert/loopback-component-realtime": "^1.0.0-rc.**6**", which needs extra configuration on `server/component-config.json`. Take a look at `driver` and `module` properties. I didn't have them in my project. Probably they're now necessary.
```json
  "@mean-expert/loopback-component-realtime": {
    "debug": true,
    "auth": true,
    "driver": {
      "name": "socket.io"
    },
    "modules": [
      "IO",
      "PubSub",
      "FireLoop",
      "WebRTCSignaler"
    ]
  }
```
 [I found the answer here](https://www.npmjs.com/package/@mean-expert/loopback-component-realtime)

**Comment by mikkoh85** [comment]
@hellraiserii I had the exact same problem when I generated new Fireloop project. Copy pasted the "driver" and "modules" stuff and it started working instantly. Confirmed.

**Comment by ittechsathish** [comment]
Hi hellraiserii, thanks for your help it is working.

**Comment by supermafete** [comment]
Great! I had the same problem too. @hellraiserii did the trick 👍
